# Generated by Django 6.1.1 on 2026-09-25 06:01

import django.db.models.functions.datetime
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FailedAuthenticationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=500)),
                ("key", models.CharField(max_length=64)),
                ("device", models.CharField(blank=True, max_length=32)),
                (
                    "time",
                    models.DateTimeField(
                        db_default=django.db.models.functions.datetime.Now()
                    ),
                ),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["key", "device", "time"],
                        name="device_cook_key_c0c68f_idx",
                    ),
                    models.Index(
                        fields=["username"],
                        name="device_cookies_username_idx",
                        opclasses=["varchar_pattern_ops"],
                    ),
                ],
            },
        ),
    ]
