# Generated by Django 6.1.1 on 2026-09-23 14:24

import django.utils.timezone
from django.db import migrations
from django.db import models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="FailedAuthenticationAttempt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("username", models.CharField(max_length=255)),
                ("device", models.CharField(blank=True, max_length=32)),
                ("time", models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                "indexes": [
                    models.Index(
                        fields=["username", "device", "time"],
                        name="device_cook_usernam_08e2b5_idx",
                    )
                ],
            },
        ),
    ]
